[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bank-marketing-ml"
version = "1.0.0"
description = "Predicting term deposit subscription using UCI Bank Marketing dataset"
requires-python = ">=3.12,<3.14"
readme = "README.md"

dependencies = [
  "pandas>=2.0,<3",
  "numpy==2.4.2",
  "scikit-learn==1.8.0",
  "xgboost==3.2.0",
  "optuna==4.7.0",
  "mlflow==3.10.0",
  "fastapi==0.134.0",
  "uvicorn[standard]==0.41.0",
  "pydantic==2.12.5",
  "python-multipart==0.0.22",
  "slowapi==0.1.9",
  "joblib==1.5.3",
  "shap==0.50.0",
  "evidently==0.7.20",
  "prometheus-client==0.24.1",
  "streamlit==1.54.0",
  "great-expectations==1.13.0",
  "pytest==9.0.2",
  "pytest-asyncio==1.3.0",
  "pytest-cov==7.0.0",
  "httpx==0.28.1",
  "locust==2.43.3",
  "ruff==0.15.4",
  "mypy==1.19.1",
  "jupyter==1.1.1",
  "matplotlib==3.10.8",
  "seaborn==0.13.2",
  "jupyterlab==4.5.5",
  "scipy==1.17.1",
  "lightgbm==4.6.0",
  "et-xmlfile==2.0.0",
  "openpyxl==3.1.5",
]

[tool.ruff]
target-version = "py312"
line-length = 100
select = ["E", "F", "I", "N", "W", "UP"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
>>>>>>> a9e269e (Initial commit for MLOps)
addopts = "-v --cov=src --cov-report=term-missing"